### ISSUE TITLE
Deletion of an array doesn't work, use pop() instead

### ISSUE THREAD

**Issue by zjplab** [samnang/solidity-examples#208]
https://github.com/samnang/solidity-examples/blob/main/contracts/sample_apps/02_address_book/AddressBook.sol

It's suggested to use pop instead of delete. `delete` will only fill with 0s.

**Comment by samnang** [comment]
@zjplab good catch 👍. It's a redundancy call because `pop` should remove the element, so we don't need to waste our gas to call `delete` just to revert to the default value for that element. I have fixed it https://github.com/samnang/solidity-examples/commit/2eeb2646db9c2b2a0150a980174881d261cd469f,
